#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { validateAgentPolicy } from './policy.mjs';

const cwd=process.cwd();
const command=process.argv[2]||'verify';
const readJson=p=>JSON.parse(readFileSync(join(cwd,p),'utf8'));
const writeJson=(p,v)=>{const full=join(cwd,p);mkdirSync(dirname(full),{recursive:true});writeFileSync(full,JSON.stringify(v,null,2)+'\n')};
const required=['AGENTS.md','BUILDOS.md','buildos.config.json','.buildos/state.json','.buildos/product.json','.buildos/architecture.json'];
function validateState(){const missing=required.filter(p=>!existsSync(join(cwd,p)));if(missing.length)throw new Error(`Missing BuildOS files: ${missing.join(', ')}`);const state=readJson('.buildos/state.json');const allowed=new Set(['not_started','in_progress','blocked','built','deployed','verified','green','red']);if(!allowed.has(state.status))throw new Error(`Invalid BuildOS status: ${state.status}`)}
function classify(check,out){const gate=String(check||'').toLowerCase();if(['lint','typecheck','test','build'].includes(gate))return gate;if(gate.includes('policy'))return'policy';if(gate.includes('auth')||gate.includes('permission'))return'authorization';const text=String(out||'').toLowerCase();if(text.includes('auth')||text.includes('permission'))return'authorization';return'gate'}
function repair(check,cmd,error,out){const r={version:1,status:'red',phase:command,failedCheck:check,command:cmd,classification:classify(check,out),error:String(error?.message||error),output:String(out||'').slice(-12000),instructions:['Identify the root cause from this evidence.','Repair the smallest complete cause; do not bypass or weaken the gate.',`Rerun the exact failed check: ${cmd||check}.`,'Continue to later BuildOS gates only after this check passes.','If deployment previously failed, redeploy the repaired exact SHA and verify production.','Preserve this RED event in BuildOS evidence.'],humanGate:false};writeJson('.buildos/repair/latest.json',r);return r}
function run(){const config=readJson('buildos.config.json');let policy;try{policy=validateAgentPolicy(cwd)}catch(e){const r=repair('policy','BuildOS agent-policy verification',e,e?.message||'');console.error(JSON.stringify(r,null,2));process.exit(1)}const active=policy.activeConflicts||policy.conflicts;if(active.length)for(const conflict of active)console.log(`⚠ policy conflict ${conflict.topic} [${conflict.scopes?.join(' ↔ ')||'repository'}]: ${conflict.resolved?`resolved by ${conflict.resolution}`:'UNRESOLVED'}`);else if(policy.conflicts.length)console.log(`✓ agent policy (${policy.conflicts.length} scoped conflicts recorded, none active for this change)`);else console.log('✓ agent policy');console.log(`→ changed files: ${policy.changedFilesKnown?(policy.changedFiles.join(', ')||'none'):'unknown; scoped policy fail-closed'}`);if(command==='verify'&&config.requireChangeRecord){const d=join(cwd,'.buildos/changes');if(!existsSync(d)||!readdirSync(d).some(f=>f.endsWith('.json')))throw new Error('BuildOS requires a change record before verification.')}for(const check of config[command]||[]){if(check==='state'){validateState();console.log('✓ state');continue}const cmd=config.commands?.[check];if(!cmd)throw new Error(`No command configured for check: ${check}`);console.log(`→ ${check}: ${cmd}`);try{const out=execSync(cmd,{cwd,encoding:'utf8',env:{...process.env,BUILDOS_RUNNING:'1'}});if(out)process.stdout.write(out);console.log(`✓ ${check}`)}catch(e){const out=`${e?.stdout||''}${e?.stderr||''}`;if(e?.stdout)process.stdout.write(String(e.stdout));if(e?.stderr)process.stderr.write(String(e.stderr));const r=repair(check,cmd,e,out);console.error(JSON.stringify(r,null,2));process.exit(1)}}}
try{run()}catch(e){const r=repair(command,null,e,e?.message||'');console.error(JSON.stringify(r,null,2));process.exit(1)}
