import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const SOURCES=[['AGENTS.md','buildos'],['CLAUDE.md','claude'],['GEMINI.md','gemini'],['.cursorrules','cursor'],['.windsurfrules','windsurf'],['.github/copilot-instructions.md','github-copilot']];
const readJson=path=>JSON.parse(readFileSync(path,'utf8'));
const sha256=text=>createHash('sha256').update(text).digest('hex');
const extractRules=content=>content.split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&(/^(?:[-*]|\d+\.)\s+/.test(x)||/\b(must|never|always|do not|don't|required|before|after|bypass|deploy|test|ship|publish|release|verification|quality gate|blocker)\b/i.test(x))).slice(0,200);
const denied=text=>/\b(never|do not|don't|must not|should not|skip)\b/i.test(text);
const RELEASE='(?:deploy(?:ment|ing)?|ship(?:ping)?|publish(?:ing)?|release|go live|live)';
const VERIFY='(?:test(?:s|ing)?|test suite|verification(?: suite)?|quality check(?:s)?|quality gate(?:s)?)';
const classify=instruction=>{const text=instruction.toLowerCase();const negated=new RegExp(`\\b(?:never|do not|don't|must not|should not)\\b[^.]{0,100}${VERIFY}[^.]{0,120}\\bbefore\\b[^.]{0,120}${RELEASE}`);const releaseFirst=new RegExp(`${RELEASE}[^.]{0,120}\\b(?:first|before)\\b[^.]{0,120}${VERIFY}|${VERIFY}[^.]{0,120}\\b(?:only )?after\\b[^.]{0,120}${RELEASE}`);const verifyFirst=new RegExp(`${VERIFY}[^.]{0,120}\\b(?:before|prior to)\\b[^.]{0,120}${RELEASE}|\\b(?:do not|don't|never|must not)\\b[^.]{0,80}${RELEASE}[^.]{0,120}\\buntil\\b[^.]{0,120}${VERIFY}`);if(negated.test(text)||releaseFirst.test(text))return{topic:'tests-before-deploy',polarity:'deny'};if(verifyFirst.test(text))return{topic:'tests-before-deploy',polarity:'require'};if(/\b(test|tests|test suite)\b/.test(text)&&/\bbefore\b/.test(text)&&/\bdeploy(?:ment|ing)?\b/.test(text))return{topic:'tests-before-deploy',polarity:denied(text)?'deny':'require'};if(/\b(failed|failing)\b[^.]{0,60}\b(quality )?gate\b[^.]{0,100}\b(stop|block|prevent)\b[^.]{0,80}(?:deploy|ship|publish|release|live)/.test(text)||/\bnever\b[^.]{0,80}\b(publish|ship|release|deploy)\b[^.]{0,80}\b(around|past)\b[^.]{0,80}\b(blocker|gate|failure)\b/.test(text))return{topic:'bypass-gate',polarity:'deny'};if(/\b(ignore|disregard|override|work around|publish around|ship around)\b[^.]{0,100}\b(blocker|gate|failure|check)\b|\b(blocker|gate|failure|check)\b[^.]{0,100}\b(ignore|disregard|override|publish anyway|ship anyway)\b/.test(text))return{topic:'bypass-gate',polarity:'allow'};if(/\bbypass\b/.test(text)&&/\bgate\b/.test(text))return{topic:'bypass-gate',polarity:denied(text)?'deny':'allow'};if(/\buse\b/.test(text)&&/\bnpm\b/.test(text))return{topic:'use-npm',polarity:denied(text)?'deny':'require'};return null};

export function validateAgentPolicy(cwd){
  const sources=SOURCES.filter(([path])=>existsSync(join(cwd,path))).map(([path,agent])=>{const content=readFileSync(join(cwd,path),'utf8');return{agent,path,format:path.endsWith('.md')?'markdown':'text',contentHash:sha256(content),rules:extractRules(content)}});
  const canonical=new Map();const cfg=readJson(join(cwd,'buildos.config.json'));const verify=cfg.verify||[];if(verify.includes('test')&&(!verify.includes('build')||verify.indexOf('test')<verify.indexOf('build')))canonical.set('tests-before-deploy','require');if(existsSync(join(cwd,'package-lock.json')))canonical.set('use-npm','require');else if(existsSync(join(cwd,'pnpm-lock.yaml'))||existsSync(join(cwd,'yarn.lock'))||existsSync(join(cwd,'bun.lock'))||existsSync(join(cwd,'bun.lockb')))canonical.set('use-npm','deny');
  const buildos=sources.find(s=>s.agent==='buildos');for(const instruction of buildos?.rules||[]){const semantic=classify(instruction);if(semantic)canonical.set(semantic.topic,semantic.polarity)}
  const rules=sources.flatMap(source=>source.rules.map((instruction,index)=>{const semantic=classify(instruction);return{id:`${source.agent}:${source.path}:${index+1}`,sourceAgent:source.agent,sourcePath:source.path,instruction,scope:'repository',enforcementLevel:source.agent==='buildos'?'canonical':'imported',topic:semantic?.topic||null,polarity:semantic?.polarity||null,conflicts:[],resolution:null,provenance:{sourcePath:source.path,contentHash:source.contentHash}}}));
  const conflicts=[];for(let i=0;i<rules.length;i++)for(let j=i+1;j<rules.length;j++){const a=rules[i],b=rules[j];if(!a.topic||a.topic!==b.topic||!a.polarity||a.polarity===b.polarity)continue;const canonicalPolarity=canonical.get(a.topic)||null,resolved=Boolean(canonicalPolarity),winner=resolved?(a.polarity===canonicalPolarity?a:b):null,loser=resolved?(winner===a?b:a):null;const c={id:`conflict-${conflicts.length+1}`,topic:a.topic,ruleIds:[a.id,b.id],canonicalPolarity,resolved,resolution:resolved?'buildos-canonical-policy':null,winnerRuleId:winner?.id||null,overriddenRuleId:loser?.id||null};conflicts.push(c);a.conflicts.push(c.id);b.conflicts.push(c.id);if(resolved){winner.resolution='canonical';loser.resolution='overridden-by-buildos'}}
  for(const rule of rules){if(rule.enforcementLevel!=='imported'||!rule.topic||!rule.polarity)continue;const canonicalPolarity=canonical.get(rule.topic);if(canonicalPolarity&&canonicalPolarity!==rule.polarity&&!rule.conflicts.length){const c={id:`conflict-${conflicts.length+1}`,topic:rule.topic,ruleIds:[rule.id],canonicalPolarity,resolved:true,resolution:'buildos-canonical-policy',winnerRuleId:'buildos:repository-evidence',overriddenRuleId:rule.id};conflicts.push(c);rule.conflicts.push(c.id);rule.resolution='overridden-by-buildos'}}
  const policy={version:2,generatedAt:new Date().toISOString(),canonicalSource:'BuildOS',sources,canonicalPolicy:Object.fromEntries(canonical),normalizedRules:rules,conflicts,unresolvedConflicts:conflicts.filter(c=>!c.resolved)};const path=join(cwd,'.buildos/agent-policy.json');mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(policy,null,2)+'\n');if(policy.unresolvedConflicts.length)throw new Error(`Unresolved AI-agent policy conflicts: ${policy.unresolvedConflicts.map(c=>c.topic).join(', ')}`);return policy;
}
